version: 0.{build}

branches:
  # blacklist
  except:
    - gh-pages

build_script:
    - ps: ./build.ps1

artifacts:
  - path: '*.nupkg'
  - path: src/SourceBrowser.Samples/bin/Release
    name: SourceBrowser.Samples
    type: zip

environment:
  NUGET_APIKEY:
    secure: eCwaphHAp/cyOVc/LxigXppNaFjC3WMFSW07rjFNuonyNg2t9pvi9cCZivqxYZBm

