version: 0.{build}

os: Visual Studio 2015 Preview

branches:
  # blacklist
  except:
    - gh-pages

build_script:
    - ps: ./build.ps1

artifacts:
  - path: '*.nupkg'
  - path: src/SourceBrowser.Samples/bin/Release
    name: SourceBrowser.Samples
    type: zip

environment:
  MSBUILD: C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
  NUGET_APIKEY:
    secure: eCwaphHAp/cyOVc/LxigXppNaFjC3WMFSW07rjFNuonyNg2t9pvi9cCZivqxYZBm
